export const text = {
  nav: '주요 내비게이션',
  browse: '둘러보기',
  makeCourse: '코스 만들기',
  nearby: '근처',
  party: '파티',
  mapButton: '지도 보기',
  eyebrow: '주말 자전거 코스',
  headline: '다음 라이딩을 계획해보세요',
  searchLabel: '어디로 가볼까요?',
  searchPlaceholder: '예시, 지역, 코스 검색',
  search: '검색',
  mapEyebrow: 'OpenStreetMap',
  mapTitle: '자전거 경로 탐색',
  close: '메인으로',
  layerLabel: '지도 레이어',
  defaultLayer: '일반 지도',
  bicycleLayer: '자전거도로',
  startPlace: '출발지',
  endPlace: '도착지',
  startPlaceholder: '출발지 검색',
  endPlaceholder: '도착지 검색',
  searchStart: '출발 검색',
  searchEnd: '도착 검색',
  reset: '마커지우기',
  routeHint: '지도를 두 번 클릭하거나 출발지와 도착지를 검색하세요.',
  bikeRoute: '자전거도로',
  shortestRoute: '최단경로',
  searching: '경로를 찾는 중...',
  routeReady: '경로 2개를 표시했습니다.',
  routeFailed: '경로를 찾지 못했습니다. 점을 더 가까이 지정해보세요.',
  noCycleways: '해당 경로에 자전거 도로가 없습니다.',
  searchFailed: '검색 결과가 없습니다.',
  regionLabel: '지역 선택',
  regionAll: '전체',
  community: '커뮤니티 활동',
  recentTitle: '최근 완주된 코스',
  recentAria: '최근 완주된 자전거 코스',
  distance: '거리',
  climb: '상승고도',
  time: '시간',
  signup: '회원가입',
  backHome: '홈으로',
  signupEyebrow: 'PedalLink 멤버십',
  signupHeadline: '당신의 라이딩이\n기록되기 시작합니다',
  signupSub: '코스 저장부터 완주 기록까지, 가입 한 번이면 충분해요.',
  signupPerk1: '나만의 코스를 저장하고 어디서든 이어서 계획',
  signupPerk2: '완주 기록과 상승고도를 자동으로 정리',
  signupPerk3: '주변 라이더들의 인기 코스를 먼저 확인',
  signupCardTitle: '회원가입',
  signupCardSub: '몇 가지 정보만 입력하면 바로 시작할 수 있어요.',
  signupName: '이름',
  signupNamePlaceholder: '라이딩에서 사용할 이름',
  signupEmail: '이메일',
  signupEmailPlaceholder: 'you@example.com',
  signupPassword: '비밀번호',
  signupPasswordPlaceholder: '8자 이상 입력',
  signupPasswordCheck: '비밀번호 확인',
  signupPasswordCheckPlaceholder: '비밀번호를 한 번 더 입력',
  signupNeedName: '이름을 입력해주세요.',
  signupNeedEmail: '올바른 이메일 주소를 입력해주세요.',
  signupNeedPassword: '비밀번호는 8자 이상이어야 합니다.',
  signupMismatch: '비밀번호가 서로 일치하지 않습니다.',
  signupDoneTitle: '가입을 환영합니다!',
  signupDoneSub: '{name}님, 이제 첫 라이딩 코스를 만들어보세요.',
  signupSocialDivider: '또는',
  signupGoogle: '구글로 로그인하기',
  signupNaver: '네이버로 로그인하기',
  login: '로그인',
  loginEyebrow: 'PedalLink 로그인',
  loginHeadline: '다시 만나서\n반가워요',
  loginSub: '로그인하고 저장한 코스와 파티를 이어서 즐겨보세요.',
  loginPerk1: '내가 저장한 코스 바로 불러오기',
  loginPerk2: '관심 있는 파티(링크)에 바로 참여',
  loginPerk3: '완주 기록을 한곳에서 관리',
  loginCardTitle: '로그인',
  loginCardSub: '이메일로 로그인하거나 소셜 계정을 이용하세요.',
  loginButton: '로그인',
  loginPasswordPlaceholder: '비밀번호 입력',
  loginNeedEmail: '올바른 이메일 주소를 입력해주세요.',
  loginNeedPassword: '비밀번호를 입력해주세요.',
  loginFailed: '로그인에 실패했습니다. 다시 시도해주세요.',
  loginToSignup: '아직 계정이 없으신가요?',
  loginSignupLink: '회원가입',
  signupToLogin: '이미 계정이 있으신가요?',
  signupLoginLink: '로그인',
  partyTitle: '파티',
  partyEyebrow: '링크',
  partySub: '저장한 코스로 같이 탈 사람을 지금 모아보세요.',
  partyMyRoutes: '내 저장 경로로 링크 만들기',
  partyNoRoutes: '저장된 경로가 없어요. 지도에서 경로를 먼저 저장해보세요.',
  partyMakeButton: '링크 만들기',
  partyOpenList: '모집 중인 링크',
  partyNoParties: '아직 열린 링크가 없어요. 첫 링크를 만들어보세요!',
  partyFormTime: '모임 시간',
  partyFormMax: '최대 인원',
  partyFormTitle: '링크 제목 (선택)',
  partyFormTitlePlaceholder: '예) 한강 노을 라이딩 같이 타요',
  partyCreate: '개설하기',
  partyCancel: '취소',
  partyFull: '모집 완료',
  partyMembers: '명',
  partyHost: '호스트',
  partyBackHome: '홈으로',
  partyApply: '참여 신청',
  partyPending: '승인 대기중',
  partyJoined: '참여 확정',
  partyClosed: '마감됨',
  partyLoginNeeded: '로그인 후 신청',
  partyApprove: '수락',
  partyReject: '거절',
  partyHostBadge: '내 파티',
  partyPendingTitle: '승인 대기',
  partyNoPending: '대기 중인 신청이 없어요.',
  partyParticipants: '참여',
};

export const seoulCenter = [37.5665, 126.978];
export const KAKAO_API_KEY = process.env.REACT_APP_KAKAO_API_KEY;

export const GU_LIST = [
  '강남구', '강동구', '강북구', '강서구', '관악구',
  '광진구', '구로구', '구리시', '금천구', '노원구',
  '도봉구', '동대문구', '동작구', '마포구', '서초구',
  '성동구', '성북구', '송파구', '양천구', '영등포구',
  '용산구', '은평구', '종로구', '중구', '중랑구',
];

export const tileLayers = {
  cyclemap: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
  mapnik: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
};

export const routes = [
  {
    title: '한강 노을 순환 코스',
    location: '서울, 반포대교',
    distance: '28.4 km',
    climb: '112 m',
    time: '1시간 24분',
    type: '시티 바이크',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '북한강 강변 라이딩',
    location: '경기 남양주',
    distance: '41.2 km',
    climb: '238 m',
    time: '2시간 08분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1471506480208-91b3a4cc78be?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '제주 해안 아침 코스',
    location: '제주 제주시',
    distance: '64.7 km',
    climb: '486 m',
    time: '3시간 35분',
    type: '투어링',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '양재천 회복 라이딩',
    location: '서울 강남',
    distance: '16.9 km',
    climb: '52 m',
    time: '48분',
    type: '전기 자전거',
    image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '남산 업힐 반복 코스',
    location: '서울 중구',
    distance: '22.1 km',
    climb: '614 m',
    time: '1시간 42분',
    type: 'MTB',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '부산 바닷바람 코스',
    location: '부산 해운대',
    distance: '37.5 km',
    climb: '174 m',
    time: '1시간 56분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1494475673543-6a6a27143fc8?auto=format&fit=crop&w=900&q=80',
  },
];
