export const text = {
  nav: '주요 내비게이션',
  browse: '둘러보기',
  feed: '피드',
  makeCourse: '코스 만들기',
  nearby: '근처',
  party: '파티',
  crew: '크루',
  mapButton: '지도 보기',
  eyebrow: '주말 자전거 코스',
  headline: '다음 라이딩을 계획해보세요',
  searchLabel: '어디로 가볼까요?',
  searchPlaceholder: '예시, 지역, 코스 검색',
  search: '검색',
  mapEyebrow: 'OpenStreetMap',
  mapTitle: '자전거 경로 탐색',
  close: '메인으로',
  layerLabel: '지도 레이어',
  defaultLayer: '일반 지도',
  bicycleLayer: '자전거도로',
  startPlace: '출발지',
  endPlace: '도착지',
  startPlaceholder: '출발지 검색',
  endPlaceholder: '도착지 검색',
  searchStart: '출발 검색',
  searchEnd: '도착 검색',
  reset: '마커지우기',
  routeHint: '지도를 두 번 클릭하거나 출발지와 도착지를 검색하세요.',
  bikeRoute: '자전거도로',
  shortestRoute: '최단경로',
  searching: '경로를 찾는 중...',
  routeReady: '경로 2개를 표시했습니다.',
  routeFailed: '경로를 찾지 못했습니다. 점을 더 가까이 지정해보세요.',
  noCycleways: '해당 경로에 자전거 도로가 없습니다.',
  searchFailed: '검색 결과가 없습니다.',
  regionLabel: '지역 선택',
  regionAll: '전체',
  community: '커뮤니티 활동',
  recentTitle: '최근 완주된 코스',
  recentAria: '최근 완주된 자전거 코스',
  distance: '거리',
  climb: '상승고도',
  time: '시간',
  signup: '회원가입',
  backHome: '홈으로',
  signupEyebrow: 'PedalLink 멤버십',
  signupHeadline: '당신의 라이딩이\n기록되기 시작합니다',
  signupSub: '코스 저장부터 완주 기록까지, 가입 한 번이면 충분해요.',
  signupPerk1: '나만의 코스를 저장하고 어디서든 이어서 계획',
  signupPerk2: '완주 기록과 상승고도를 자동으로 정리',
  signupPerk3: '주변 라이더들의 인기 코스를 먼저 확인',
  signupCardTitle: '회원가입',
  signupCardSub: '몇 가지 정보만 입력하면 바로 시작할 수 있어요.',
  signupName: '이름',
  signupNamePlaceholder: '라이딩에서 사용할 이름',
  signupEmail: '이메일',
  signupEmailPlaceholder: 'you@example.com',
  signupPassword: '비밀번호',
  signupPasswordPlaceholder: '8자 이상 입력',
  signupPasswordCheck: '비밀번호 확인',
  signupPasswordCheckPlaceholder: '비밀번호를 한 번 더 입력',
  signupNeedName: '이름을 입력해주세요.',
  signupNeedEmail: '올바른 이메일 주소를 입력해주세요.',
  signupNeedPassword: '비밀번호는 8자 이상이어야 합니다.',
  signupMismatch: '비밀번호가 서로 일치하지 않습니다.',
  signupDoneTitle: '가입을 환영합니다!',
  signupDoneSub: '{name}님, 이제 첫 라이딩 코스를 만들어보세요.',
  signupSocialDivider: '또는',
  signupGoogle: '구글로 로그인하기',
  signupNaver: '네이버로 로그인하기',
  socialPreparing: '소셜 로그인은 준비 중입니다. 이메일로 로그인해주세요.',
  login: '로그인',
  logout: '로그아웃',
  menuProfile: '프로필',
  menuSettings: '설정',
  menuComingSoon: '준비 중',
  loginEyebrow: 'PedalLink 로그인',
  loginHeadline: '다시 만나서\n반가워요',
  loginSub: '로그인하고 저장한 코스와 파티를 이어서 즐겨보세요.',
  loginPerk1: '내가 저장한 코스 바로 불러오기',
  loginPerk2: '관심 있는 파티(링크)에 바로 참여',
  loginPerk3: '완주 기록을 한곳에서 관리',
  loginCardTitle: '로그인',
  loginCardSub: '이메일로 로그인하거나 소셜 계정을 이용하세요.',
  loginButton: '로그인',
  loginPasswordPlaceholder: '비밀번호 입력',
  loginNeedEmail: '올바른 이메일 주소를 입력해주세요.',
  loginNeedPassword: '비밀번호를 입력해주세요.',
  loginFailed: '로그인에 실패했습니다. 다시 시도해주세요.',
  loginToSignup: '아직 계정이 없으신가요?',
  loginSignupLink: '회원가입',
  signupToLogin: '이미 계정이 있으신가요?',
  signupLoginLink: '로그인',
  partyTitle: '파티',
  partyEyebrow: '링크',
  partySub: '저장한 코스로 같이 탈 사람을 지금 모아보세요.',
  partyNoRoutes: '저장된 경로가 없어요. 지도에서 경로를 먼저 저장해보세요.',
  routeListLoginNeeded: '로그인 후 이용할 수 있습니다.',
  partyMakeButton: '링크 만들기',
  partyCreateSub: '저장한 코스를 골라 같이 탈 사람을 모아보세요.',
  partyCreateFailed: '링크를 만들지 못했습니다.',
  partyOpenList: '모집 중인 링크',
  partyNoParties: '아직 열린 링크가 없어요. 첫 링크를 만들어보세요!',
  partyViewSwitch: '파티 화면 전환',
  partyViewRoom: '내 파티',
  partyRoomEmptyTitle: '참여 중인 파티가 없어요',
  partyRoomEmptySub: '모집 중인 링크에 참여하거나, 내 코스로 링크를 열어보세요.',
  partyRoomEmptyLogin: '로그인하면 참여 중인 파티를 여기서 볼 수 있어요.',
  partyViewList: '모집 중인 링크',
  partyViewListHint: '참여할 파티 찾기',
  partyOpenRoom: '대기방 열기',
  partyRidingNow: '라이딩 중',
  partyCountUnit: '개 참여 중',
  partyViewRoomHint: '참여 중인 파티 없음',
  partyFormTime: '모임 시간',
  partyFormMax: '최대 인원',
  partyFormTitle: '링크 제목 (선택)',
  partyFormTitlePlaceholder: '예) 한강 노을 라이딩 같이 타요',
  partyCreate: '개설하기',
  partyCancel: '취소',
  partyFull: '모집 완료',
  partyMembers: '명',
  partyHost: '호스트',
  partyBackHome: '홈으로',
  partyApply: '참여 신청',
  partyPending: '승인 대기중',
  partyJoined: '참여 확정',
  partyClosed: '마감됨',
  partyLoginNeeded: '로그인 후 신청',
  partyApprove: '수락',
  partyReject: '거절',
  partyHostBadge: '내 파티',
  partyPendingTitle: '승인 대기',
  partyNoPending: '대기 중인 신청이 없어요.',
  partyParticipants: '참여',
  partyStartRide: '라이딩 시작',
  partyJoinRide: '라이딩 합류',
  partyEnded: '종료된 라이딩',
  partyDelete: '삭제',
  partyDeleteConfirm: '이 링크를 삭제할까요? 참가 신청도 함께 사라집니다.',
  partyDeleteYes: '삭제',
  partyDeleteNo: '취소',
  partyDeleteFailed: '삭제하지 못했습니다.',
  partyRideStartFailed: '라이딩을 시작하지 못했습니다.',
  partyLoadFailed: '파티 목록을 불러오지 못했습니다. 서버 상태를 확인해 주세요.',
  rideStart: '라이딩 시작',
  rideStop: '라이딩 종료',
  rideEndedParty: '라이딩을 종료하고 파티를 마감했습니다.',
  rideEndedSolo: '라이딩을 종료했습니다.',
  partyRideBanner: '파티 라이딩 중 — 멤버 위치만 표시됩니다',
  partyRideExit: '파티 나가기',
  heroScrollCue: '아래로 스크롤',
  featureEyebrow: '핵심 기능',
  featureTitle: '혼자 정하던 라이딩을, 다르게',
  featureLead: 'PedalLink는 근처 라이더와의 실시간 연결과 똑똑한 경로 계산으로, 라이딩을 준비하는 방식을 바꿉니다.',
  featureAria: 'PedalLink 핵심 기능',
  instantEyebrow: '즉석 링크',
  instantTitle: '지금 근처에서 바로',
  instantSub: '주변에 있는 라이더와 지금 바로 연결해서 함께 달려요. 약속을 미리 잡지 않아도, 마음이 맞으면 그대로 출발합니다.',
  instantCta: '지금 링크 만들기',
  instantAria: '지금 모집 중인 즉석 링크',
  plannedEyebrow: '미리 모집',
  plannedTitle: '미리 모아서 함께',
  plannedSub: '날짜와 코스를 정해두고 같이 탈 사람을 모아요. 호스트가 신청을 확인하고 수락하면 참여가 확정됩니다.',
  plannedCta: '모집 중인 링크 보기',
  plannedAria: '미리 모집 중인 링크',
  plannedHostLabel: '호스트',
  plannedWhenLabel: '출발',
  closingTitle: '오늘, 어디까지 달려볼까요?',
  closingSub: '지도에서 코스를 직접 그려 저장하고, 그 코스로 링크를 열어보세요.',
  closingMap: '지도 보기',
  closingParty: '파티 보기',
  browseEyebrow: '라이더 피드',
  feedTitle: '피드',
  browseLoading: '불러오는 중…',
  browseNoFeed: '아직 공유된 코스가 없어요. 지도에서 경로를 저장하면 여기에 올라옵니다.',
  browseLoadFailed: '피드를 불러오지 못했습니다.',
  browseLike: '좋아요',
  browseUnlike: '좋아요 취소',
  browseComment: '댓글',
  browseShare: '공유',
  browseSave: '저장',
  browseOpenMap: '지도로 보기',
  browsePreparing: '준비 중인 기능입니다',
  browseCompose: '게시물 올리기',
  browseComposeTitle: '게시물 올리기',
  browseComposeSub: '저장한 경로를 골라 소개 문구를 남겨보세요.',
  browseComposeRoute: '경로 선택',
  browseComposeDesc: '문구',
  browseComposeDescPlaceholder: '예) 잠실에서 여의도까지 한강 야경을 즐기며 달리는 코스입니다.',
  browseComposeTags: '해시태그 (선택)',
  browseComposeTagsPlaceholder: '예) #야경 #초보코스 #한강',
  browseComposePhoto: '사진 (선택)',
  browseComposePhotoAdd: '사진 추가',
  browseComposePhotoBusy: '사진 줄이는 중…',
  browseComposePhotoRemove: '사진 빼기',
  browseComposePhotoAlt: '올릴 사진 미리보기',
  browsePhotoTypeError: '이미지 파일만 올릴 수 있어요.',
  browsePhotoTooBig: '사진이 너무 큽니다. 8MB 이하로 올려주세요.',
  browsePhotoReadError: '사진을 읽지 못했어요. 다른 사진으로 시도해주세요.',
  browseComposeSubmit: '올리기',
  browseComposeCancel: '취소',
  browseComposeNoRoutes: '저장된 경로가 없어요. 지도에서 경로를 먼저 저장해주세요.',
  browseComposeFailed: '게시물을 올리지 못했습니다.',
};

// ── 피드 사이드바 (인기 코스 / 활발한 지역) ──────────
export const feedSide = {
  aria: '인기 코스와 활발한 지역',
  topRoutes: '인기 코스',
  topRegions: '활발한 지역',
  seeAll: '지도에서 보기',
  likes: '좋아요',
  riders: '라이더',
  courses: '코스',
  unit: '명',
  note: '최근 올라온 게시물을 기준으로 집계했어요.',
};

// ── 크루(정기 모임) ─────────────────────────────────
export const crew = {
  tabsLabel: '크루 화면 전환',
  findTab: '크루 찾기',
  findTabHint: '지역·요일로 탐색',
  mineTab: '내 크루',
  crewUnit: '개 참여 중',
  noMyCrew: '가입한 크루 없음',
  createCrew: '크루 만들기',

  regionLabel: '지역',
  scheduleLabel: '일정',
  memberLabel: '인원',
  noSchedule: '일정 미정',

  join: '가입 신청',
  joined: '가입됨',
  pending: '승인 대기중',
  leader: '리더',
  me: '나',

  backToList: '크루 목록',
  chatTitle: '크루 채팅',
  chatEmpty: '아직 메시지가 없어요. 첫 메시지를 보내보세요!',
  chatPlaceholder: '메시지를 입력하세요…',
  chatSend: '전송',
  memberListTitle: '크루 멤버',
  noMembers: '아직 멤버 정보가 없어요.',
  controlTitle: '크루 관리',
  memberPanelTitle: '크루 메뉴',
  openRide: '이번 주 라이딩 열기',
  upcomingTitle: '예정된 라이딩',
  noUpcoming: '예정된 라이딩이 없어요.',
  attend: '참여',
  attendYes: '이번 주 참석',
  attendNo: '불참',
  attendUnknown: '미정',
  settings: '크루 설정',
  manageRequests: '가입 요청 관리',
  noPending: '대기 중인 가입 신청이 없어요.',
  approve: '수락',
  reject: '거절',
  requestActionFailed: '처리하지 못했어요. 다시 시도해주세요.',
  leave: '크루 나가기',

  soon: '곧',
  soonHint: '준비 중이에요.',
  noCrew: '아직 만들어진 크루가 없어요.',
  noMyCrewLong: '아직 가입한 크루가 없어요. 크루 찾기에서 참여해보세요.',
  loadFailed: '크루 목록을 불러오지 못했습니다.',
  joinFailed: '가입 신청에 실패했습니다.',
  leaveFailed: '크루를 나가지 못했습니다.',
};

export const seoulCenter = [37.5665, 126.978];
export const KAKAO_API_KEY = import.meta.env.VITE_KAKAO_API_KEY;

export const GU_LIST = [
  '강남구', '강동구', '강북구', '강서구', '관악구',
  '광진구', '구로구', '구리시', '금천구', '노원구',
  '도봉구', '동대문구', '동작구', '마포구', '서초구',
  '성동구', '성북구', '송파구', '양천구', '영등포구',
  '용산구', '은평구', '종로구', '중구', '중랑구',
];

export const tileLayers = {
  cyclemap: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
  mapnik: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '&copy; OpenStreetMap contributors',
  },
};

// 홈 화면 "핵심 기능 소개" 섹션 데이터 (아이콘은 FeatureSection 에서 매핑)
export const features = [
  {
    key: 'match',
    title: '위치기반 실시간 매칭',
    desc: '지금 근처에 있는 라이더를 실시간으로 찾아, 즉석에서 함께 달릴 파티로 연결해요.',
  },
  {
    key: 'route',
    title: '경로 최적화',
    desc: '자전거도로를 우선으로, 출발지에서 목적지까지 안전하고 빠른 길을 자동으로 계산해요.',
  },
];

// 홈 화면 "지금 근처에서 바로" 섹션용 예시 데이터 (디자인용 정적 데이터)
export const instantLinks = [
  {
    title: '퇴근길 한강 20km 가볍게',
    routeName: '한강 노을 순환 코스',
    startLabel: '반포한강공원 잠수교 입구',
    nearbyLabel: '1.2km 근처',
    leaveInLabel: '12분 뒤 출발',
    members: 3,
    maxMembers: 6,
  },
  {
    title: '양재천 저녁 회복 주행',
    routeName: '양재천 회복 라이딩',
    startLabel: '양재시민의숲 정문',
    nearbyLabel: '2.8km 근처',
    leaveInLabel: '35분 뒤 출발',
    members: 2,
    maxMembers: 4,
  },
  {
    title: '남산 한 바퀴 치고 옵니다',
    routeName: '남산 업힐 반복 코스',
    startLabel: '숭례문 광장',
    nearbyLabel: '4.1km 근처',
    leaveInLabel: '1시간 뒤 출발',
    members: 4,
    maxMembers: 5,
  },
];

// 홈 화면 "미리 모아서 함께" 섹션용 예시 데이터 (디자인용 정적 데이터)
export const plannedLinks = [
  {
    title: '주말 북한강 라이딩 같이 가요',
    routeName: '북한강 강변 라이딩',
    whenLabel: '8월 15일 토 오전 7시',
    members: 4,
    maxMembers: 8,
    hostName: '라이더A',
  },
  {
    title: '남산 업힐 도전 링크',
    routeName: '남산 업힐 반복 코스',
    whenLabel: '8월 16일 일 오전 6시 30분',
    members: 3,
    maxMembers: 4,
    hostName: '바이크박',
  },
  {
    title: '제주 해안 아침 투어링',
    routeName: '제주 해안 아침 코스',
    whenLabel: '8월 22일 토 오전 8시',
    members: 5,
    maxMembers: 10,
    hostName: '한강러너',
  },
];

export const routes = [
  {
    title: '한강 노을 순환 코스',
    location: '서울, 반포대교',
    distance: '28.4 km',
    climb: '112 m',
    time: '1시간 24분',
    type: '시티 바이크',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '북한강 강변 라이딩',
    location: '경기 남양주',
    distance: '41.2 km',
    climb: '238 m',
    time: '2시간 08분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1471506480208-91b3a4cc78be?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '제주 해안 아침 코스',
    location: '제주 제주시',
    distance: '64.7 km',
    climb: '486 m',
    time: '3시간 35분',
    type: '투어링',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '양재천 회복 라이딩',
    location: '서울 강남',
    distance: '16.9 km',
    climb: '52 m',
    time: '48분',
    type: '전기 자전거',
    image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '남산 업힐 반복 코스',
    location: '서울 중구',
    distance: '22.1 km',
    climb: '614 m',
    time: '1시간 42분',
    type: 'MTB',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
  },
  {
    title: '부산 바닷바람 코스',
    location: '부산 해운대',
    distance: '37.5 km',
    climb: '174 m',
    time: '1시간 56분',
    type: '로드 바이크',
    image: 'https://images.unsplash.com/photo-1494475673543-6a6a27143fc8?auto=format&fit=crop&w=900&q=80',
  },
];

// ── 홈 개선 섹션 (pen 초안 포팅) ──────────────────
// 히어로 아래 섹션들의 문구·구성. 이미지는 따로 제작해 .homeImgSlot 자리에 넣는다.

// S2 · 코스 만들기 (쇼케이스)
export const homeCourse = {
  id: 'instant',            // 히어로 하단 화살표(#instant)가 이 섹션으로 스크롤
  variant: 'wash',
  eyebrow: '코스 만들기',
  title: '지도 위에서 바로 코스를 그리세요',
  sub: '출발지와 도착지를 찍으면 거리·고도·예상 시간이 자동으로 계산됩니다.',
  imageLabel: '이미지 자리 — 지도/경로 편집 화면',
  features: [
    { title: '코스 그리기', desc: '지도 위에 출발지와 도착지를 찍어 보세요.', image: '/images/course/draw.png', alt: '한강 지도에서 출발 지점을 지정한 실제 코스 편집 화면' },
    { title: '실시간 계산', desc: '거리·고도·예상 시간을 바로 확인하세요.', image: '/images/course/calculate.png', alt: '거리 0.4km, 상승 3m, 예상 시간 1분이 표시된 실제 계산 결과' },
    { title: '저장한 코스', desc: '마음에 든 코스를 저장해 다시 꺼내 쓰세요.', image: '/images/course/saved.png', alt: '한강 코스와 경로가 저장되었습니다 알림이 표시된 실제 저장 완료 화면' },
  ],
};

// S3 · 실시간 매칭 (좌우 분할)
export const homeMatch = {
  eyebrow: '실시간 매칭',
  title: '근처 라이더와 지금 바로 연결',
  sub: '위치를 공유하면 반경 안의 라이더가 지도에 실시간으로 표시됩니다.',
  imageLabel: '이미지 자리 — 실시간 매칭 지도',
  points: ['반경 안 라이더 자동 감지', '접근·이탈 알림', '파티 멤버와 위치 공유'],
};

// S4 · 함께 달리기 (쇼케이스)
export const homeParty = {
  variant: 'wash',
  eyebrow: '함께 달리기',
  title: '혼자보다 함께, 파티 라이딩',
  sub: '코스를 정하고 라이더를 초대하세요. 출발부터 도착까지 함께 달립니다.',
  imageLabel: '이미지 자리 — 파티/함께 달리기 화면',
  features: [
    { title: '파티 개설', desc: '코스를 걸고 모집 인원을 정해 파티를 열어요.' },
    { title: '승인·참여', desc: '호스트가 참가 신청을 확인하고 함께 달릴 멤버를 확정해요.' },
    { title: '같이 출발', desc: '호스트가 시작하면 모든 멤버 화면이 동시에 출발합니다.' },
  ],
};

// S5 · 둘러보기 (좌우 분할 · 반전)
export const homeBrowse = {
  eyebrow: '둘러보기',
  title: '라이더들의 코스를 둘러보세요',
  sub: '다른 라이더가 완주한 코스를 피드에서 구경하고 저장하세요.',
  points: ['썸네일·거리·고도 한눈에', '좋아요로 인기 코스 확인', '마음에 든 코스 저장'],
};

// 홈 "둘러보기" 섹션의 흐르는 피드 미리보기 (FeedMarquee 전용 정적 데이터).
// 실제 피드를 부르지 않는다 — 홈은 로그인 전에도 뜨고, 지도 타일까지 얹으면 무거워진다.
export const homeFeedSamples = [
  {
    photo: '/feed/hanriver-sunset.jpg',
    author: '정우', place: '반포한강공원', time: '42분',
    body: '반포에서 여의도까지 야경 보면서 천천히 달렸어요. 초보도 부담 없는 코스입니다.',
    routeName: '한강 야경 코스', distance: '12.4km', ascend: '50m', duration: '48분',
    likes: 117, comments: 32, shares: 8, tone: '#e9f2f7',
    line: 'M28 196 C 92 168, 116 214, 172 138 S 252 92, 300 58',
    start: [28, 196], end: [300, 58],
  },
  {
    photo: '/feed/mountain-view.jpg',
    author: '소연', place: '남산공원', time: '3시간',
    body: '남산 업힐 3바퀴. 다리는 남아나질 않지만 정상 뷰는 진짜 좋습니다.',
    routeName: '남산 업힐 반복', distance: '8.2km', ascend: '420m', duration: '41분',
    likes: 91, comments: 11, shares: 3, tone: '#eaf3ec',
    line: 'M40 210 C 96 178, 108 86, 168 104 S 254 190, 296 72',
    start: [40, 210], end: [296, 72],
  },
  {
    photo: '/feed/hanriver-bridge.jpg',
    author: '민재', place: '잠수교 북단', time: '6시간',
    body: '퇴근하고 가볍게 한 바퀴. 평일 저녁이라 사람도 적고 좋았어요.',
    routeName: '퇴근길 순환', distance: '6.8km', ascend: '12m', duration: '22분',
    likes: 46, comments: 7, shares: 2, tone: '#f1eff9',
    line: 'M52 84 C 116 62, 158 158, 214 150 S 282 196, 292 168',
    start: [52, 84], end: [292, 168],
  },
  {
    photo: '/feed/cafe-stop.jpg',
    author: '세훈', place: '아라뱃길', time: '어제',
    body: '아라뱃길 왕복 완주했습니다. 바람만 없으면 정말 편한 코스예요.',
    routeName: '아라뱃길 완주', distance: '31.0km', ascend: '38m', duration: '1시간 52분',
    likes: 38, comments: 5, shares: 1, tone: '#faf1e8',
    line: 'M24 130 C 88 124, 140 66, 196 94 S 268 150, 304 128',
    start: [24, 130], end: [304, 128],
  },
  {
    photo: '/feed/mtb-ridge.jpg',
    author: '유진', place: '뚝섬유원지', time: '어제',
    body: '뚝섬 한 바퀴 돌고 왔어요. 벚꽃 시즌엔 더 예쁠 것 같습니다.',
    routeName: '뚝섬 한바퀴', distance: '18.5km', ascend: '24m', duration: '1시간 6분',
    likes: 24, comments: 3, shares: 1, tone: '#e9f2f7',
    line: 'M60 70 C 96 150, 156 178, 200 130 S 268 68, 288 152',
    start: [60, 70], end: [288, 152],
  },
];


// S6 · CTA
export const homeCta = {
  title: '지금 함께 달릴 라이더를 찾아보세요',
  sub: '가입하고 첫 코스를 만들어 파티를 열어보세요.',
  primary: '시작하기',
  secondary: '코스 둘러보기',
};

// S7 · 푸터
export const homeFooter = {
  tagline: '자전거 동호회와 즉석 파티를\n한곳에서.',
  columns: [
    { head: '둘러보기', items: ['피드', '인기 코스'] },
    { head: '파티', items: ['파티 찾기', '파티 열기'] },
    { head: '코스', items: ['코스 만들기', '내 저장 경로'] },
  ],
  copyright: '© 2026 PedalLink',
};

// ── 계정 페이지 (프로필/설정 뼈대) ──────────────────
export const account = {
  memberFallback: 'PedalLink 회원',
  profileActivityTitle: '내 활동',
  profileActivity: ['내 코스', '주행 기록', '참여한 파티'],
  settingsAccountTitle: '계정',
  settingsRows: ['이메일 변경', '비밀번호 변경', '위치 공유', '알림 설정'],
  soon: '준비 중',
};

// ── 파티 플로팅 도크 (모집중/소속 시 우측 하단) ──────
export const partyDock = {
  title: '내 파티',
  membersTab: '멤버',
  chatTab: '채팅',
  chatEmpty: '아직 메시지가 없어요. 첫 메시지를 보내보세요!',
  chatPlaceholder: '메시지를 입력하세요…',
  chatSend: '전송',
  locOff: '위치 꺼짐',
  hostBadge: '호스트',
  meBadge: '나',
  profileSoon: '상세 프로필은 준비 중이에요.',
  memberCountUnit: '명',
  emptyMembers: '아직 참여 확정된 멤버가 없어요.',
  emptyTitle: '아직 참여한 파티가 없어요',
  emptySub: '파티에 참여하면 여기서 멤버와 거리·프로필을 볼 수 있어요.',
  findParty: '파티 찾기',
  nearTab: '근처',
  partyTab: '파티',
  createInstant: '즉석 파티 만들기',
  createRouteLabel: '코스 선택',
  maxLabel: '최대 인원',
  createNoRoutes: '저장된 코스가 없어요. 지도에서 경로를 먼저 저장하세요.',
  createBtn: '파티 만들기',
  createFailed: '파티를 만들지 못했어요.',
  viewAllParties: '전체 파티 보기',
  noPartyTitle: '아직 참여한 파티가 없어요',
  chatNeedParty: '파티에 참여하면 멤버와 채팅할 수 있어요.',
  ridingOpen: '라이딩 화면 열기',
  findTitle: '근처 라이더',
  nearbyPrefix: '근처',
  memberTag: '파티원',
  locationShare: '내 위치 공유',
  locationShareOn: '켜짐 — 다른 라이더가 나를 찾을 수 있어요',
  locationShareOff: '꺼짐 — 나는 목록에 안 보여요 (남은 볼 수 있음)',
  near: '접근 중',
  nearEmpty: '주변에 위치 공유 중인 라이더가 없어요.',
  myPartyGroup: '내 파티',
  nearbyGroup: '주변 라이더',
  applyFailed: '신청하지 못했어요. 다시 시도해주세요.',
  soloStart: '혼자 타기',
  soloPickerTitle: '개인 라이딩 시작',
  soloFreeBtn: '자유주행 시작',
  soloOr: '또는 코스를 선택해서 시작',
  soloLoading: '코스 불러오는 중…',
  soloNoRoutes: '저장된 코스가 없어요.',
  soloStartCourseBtn: '이 코스로 시작',
  soloCancel: '취소',
  matchRequest: '매칭 신청',
  matchSent: '신청함',
  matchRequestedSuffix: '님이 매칭 신청했어요',
  matchMoreSuffix: '건 더 있어요',
  matchAccept: '수락',
  matchReject: '거절',
  readyDone: '준비 완료',
  readyWaiting: '준비 중',
};

// 파티 룸(채팅+멤버목록+방장 제어판 오버레이) 전용 텍스트
export const partyRoom = {
  waitingRoom: '라이딩 대기방',
  readyDone: '준비 완료',
  readyWaiting: '준비 중',
  chatTitle: '채팅방',
  memberListTitle: '라이딩 대기 중인 사람들',
  emptySlot: '빈 자리',
  readyCancel: '준비 취소',
  inviteLabel: '모집 중인 링크',
  inviteCopy: '복사',
  inviteCopied: '복사됨!',
  nearChatTab: '근처 채팅',
  nearChatHint: '주변 라이더와 바로 대화하는 기능이에요. 준비 중입니다.',
  voiceChat: '음성 대화',
  voiceSoonHint: '준비 중이에요.',
  soonBadge: '곧',
  controlTitle: '방장 제어판',
  startRide: '라이딩 시작!',
  goToRide: '라이딩 화면으로 이동',
  settingsSoon: '파티 설정',
  settingsSoonHint: '준비 중이에요.',
  editRouteSoon: '경로 수정',
  editRouteSoonHint: '준비 중이에요.',
  manageRequests: '참가 요청 관리',
  waitingCount: '대기',
  noPendingShort: '대기 중인 신청이 없어요.',
  leaveRoom: '방 나가기',
  leaveConfirm: '이 파티에서 나갈까요?',
  deleteRoom: '파티 삭제',
  deleteConfirm: '이 파티를 삭제할까요? 모든 참가 신청도 함께 사라집니다.',
  confirmYes: '확인',
  confirmNo: '취소',
  hostOnlyHint: '방장만 사용할 수 있어요.',
  memberOnlyPanel: '참가자 메뉴',
  actionFailed: '처리하지 못했어요. 다시 시도해주세요.',
};
